/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef GreeterService_H
#define GreeterService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "GeeterService_types.h"

namespace sim {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class GreeterServiceIf {
 public:
  virtual ~GreeterServiceIf() {}

  /**
   * A method definition looks like C code. It has a return type, arguments,
   * and optionally a list of exceptions that it may throw. Note that argument
   * lists and exception lists are specified using the exact same syntax as
   * field lists in struct or exception definitions.
   * 
   * @param hello
   */
  virtual void greet(std::string& _return, const std::string& hello) = 0;
};

class GreeterServiceIfFactory {
 public:
  typedef GreeterServiceIf Handler;

  virtual ~GreeterServiceIfFactory() {}

  virtual GreeterServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(GreeterServiceIf* /* handler */) = 0;
  };

class GreeterServiceIfSingletonFactory : virtual public GreeterServiceIfFactory {
 public:
  GreeterServiceIfSingletonFactory(const ::std::shared_ptr<GreeterServiceIf>& iface) : iface_(iface) {}
  virtual ~GreeterServiceIfSingletonFactory() {}

  virtual GreeterServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(GreeterServiceIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<GreeterServiceIf> iface_;
};

class GreeterServiceNull : virtual public GreeterServiceIf {
 public:
  virtual ~GreeterServiceNull() {}
  void greet(std::string& /* _return */, const std::string& /* hello */) override {
    return;
  }
};

typedef struct _GreeterService_greet_args__isset {
  _GreeterService_greet_args__isset() : hello(false) {}
  bool hello :1;
} _GreeterService_greet_args__isset;

class GreeterService_greet_args {
 public:

  GreeterService_greet_args(const GreeterService_greet_args&);
  GreeterService_greet_args& operator=(const GreeterService_greet_args&);
  GreeterService_greet_args() noexcept
                            : hello() {
  }

  virtual ~GreeterService_greet_args() noexcept;
  std::string hello;

  _GreeterService_greet_args__isset __isset;

  void __set_hello(const std::string& val);

  bool operator == (const GreeterService_greet_args & rhs) const
  {
    if (!(hello == rhs.hello))
      return false;
    return true;
  }
  bool operator != (const GreeterService_greet_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const GreeterService_greet_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class GreeterService_greet_pargs {
 public:


  virtual ~GreeterService_greet_pargs() noexcept;
  const std::string* hello;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _GreeterService_greet_result__isset {
  _GreeterService_greet_result__isset() : success(false) {}
  bool success :1;
} _GreeterService_greet_result__isset;

class GreeterService_greet_result {
 public:

  GreeterService_greet_result(const GreeterService_greet_result&);
  GreeterService_greet_result& operator=(const GreeterService_greet_result&);
  GreeterService_greet_result() noexcept
                              : success() {
  }

  virtual ~GreeterService_greet_result() noexcept;
  std::string success;

  _GreeterService_greet_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const GreeterService_greet_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const GreeterService_greet_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const GreeterService_greet_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _GreeterService_greet_presult__isset {
  _GreeterService_greet_presult__isset() : success(false) {}
  bool success :1;
} _GreeterService_greet_presult__isset;

class GreeterService_greet_presult {
 public:


  virtual ~GreeterService_greet_presult() noexcept;
  std::string* success;

  _GreeterService_greet_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class GreeterServiceClient : virtual public GreeterServiceIf {
 public:
  GreeterServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  GreeterServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  /**
   * A method definition looks like C code. It has a return type, arguments,
   * and optionally a list of exceptions that it may throw. Note that argument
   * lists and exception lists are specified using the exact same syntax as
   * field lists in struct or exception definitions.
   * 
   * @param hello
   */
  void greet(std::string& _return, const std::string& hello) override;
  void send_greet(const std::string& hello);
  void recv_greet(std::string& _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class GreeterServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<GreeterServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (GreeterServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_greet(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  GreeterServiceProcessor(::std::shared_ptr<GreeterServiceIf> iface) :
    iface_(iface) {
    processMap_["greet"] = &GreeterServiceProcessor::process_greet;
  }

  virtual ~GreeterServiceProcessor() {}
};

class GreeterServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  GreeterServiceProcessorFactory(const ::std::shared_ptr< GreeterServiceIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< GreeterServiceIfFactory > handlerFactory_;
};

class GreeterServiceMultiface : virtual public GreeterServiceIf {
 public:
  GreeterServiceMultiface(std::vector<std::shared_ptr<GreeterServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~GreeterServiceMultiface() {}
 protected:
  std::vector<std::shared_ptr<GreeterServiceIf> > ifaces_;
  GreeterServiceMultiface() {}
  void add(::std::shared_ptr<GreeterServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  /**
   * A method definition looks like C code. It has a return type, arguments,
   * and optionally a list of exceptions that it may throw. Note that argument
   * lists and exception lists are specified using the exact same syntax as
   * field lists in struct or exception definitions.
   * 
   * @param hello
   */
  void greet(std::string& _return, const std::string& hello) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->greet(_return, hello);
    }
    ifaces_[i]->greet(_return, hello);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class GreeterServiceConcurrentClient : virtual public GreeterServiceIf {
 public:
  GreeterServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  GreeterServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  /**
   * A method definition looks like C code. It has a return type, arguments,
   * and optionally a list of exceptions that it may throw. Note that argument
   * lists and exception lists are specified using the exact same syntax as
   * field lists in struct or exception definitions.
   * 
   * @param hello
   */
  void greet(std::string& _return, const std::string& hello) override;
  int32_t send_greet(const std::string& hello);
  void recv_greet(std::string& _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
